apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APPLICATION_NAME}
spec:
  schedule: "0 0 * * 0"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: ${APPLICATION_NAME}
              image: ${CONTAINER_IMAGE_TAGGED}
              env:
                - name: FINANCES_API_URL
                  value: http://finances
                - name: FINANCES_API_ACCOUNT_ID
                  value: "8"
                - name: LOKI_URL
                  value: http://loki.monitoring:3100
              envFrom:
                - secretRef:
                    name: nissay-401k-scraper-env-from-vault
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nissay-401k-scraper-env
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: nissay-401k-scraper-env-from-vault
    creationPolicy: Orphan
  dataFrom:
    - extract:
        key: nissay-401k-scraper
